* Biblioteca
Crear un diseño ER que permita gestionar los datos de una biblioteca de modo que:

- Las personas socias de la biblioteca disponen de un código de socio y además necesitar almacenar su dni, dirección, teléfono, nombre y apellidos
- La biblioteca almacena libros que presta a los socios y socias, de ellos se almacena su título, su editorial, el año en el que se escribió el libro, el nombre completo del autor (o autores), el año en que se editó y en qué editorial fue y el ISBN.
- Necesitamos poder indicar si un volumen en la biblioteca está deteriorado o no
- Queremos controlar cada préstamo que se realiza almacenando la fecha en la que se realiza, la fecha tope para devolver (que son 15 días más que la fecha inicial) y la fecha real en la que se devuelve el libro


* Menú diario

Crear un esquema ER que represente un modelo para llevar los datos que maneja un restaurante de menús diarios. Teniendo en cuenta que:
- Sólo interesa llevar los datos de los menús diarios a la hora de la comida, nada más del restaurante
- Cada menús se compone de una serie de posibles platos. Cada plato se puede repetir en diferentes días. Los platos pueden ser primer plato, segundo plato o postre.
- De cada plato se almacena el nombre (por ejemplo /Arroz negro con setas/) y una pequeña descripción.
- De los menús almacenamos la fecha en la que se ofrece el menú, y el número de raciones de cada plato que se han servido ese día.
- Se almacena también la temperatura que hacía el día del menú para así poder analizar las temperaturas y los platos exitosos


* Horario
Crear un esquema ER que represente el funcionamiento de un centro escolar de formación profesional, teniendo en cuenta que:

- Sólo interesa llevar el control de ocupación de las aulas en el horario escolar
- El horario es de seis horas diarias y en la base de datos simplemente se anota si es la primera, segunda,… y el día de la semana del que hablamos (por ejemplo miércoles a tercera hora)
- Las asignaturas tienen un nombre, un código interno del centro y un código europeo.
- La misma asignatura se puede impartir en dos ciclos distintos y en ese caso tendría el mismo código europeo y nombre, pero el código interno sería distinto. Hace falta saber en qué curso del ciclo se imparte la asignatura
- Los ciclos tienen un nombre, pueden ser de grado superior,de grado medio o de iniciación profesional
- Las asignaturas en cada momento ocupan un aula, del que tenemos que almacenar un código de aula, un nombre (que no se repite), un número de aula (que tampoco se repite) y los metros que tiene. A una hora concreta de la semana, el aula puede estar vacía o bien ocuparse, pero sólo se puede ocupar por una asignatura
- Necesitamos saber y anotar en la base de datos si una asignatura requiere que antes se hayan aprobado otras, para poder matricularse en ella. Por ejemplo, Ampliación de Matemáticas de 2º a lo mejor requiere aprobar Matemáticas de 1º. Puede requerirse terminar más de una asignatura previamente para poder matricularse de una concreta.
- De los profesores se almacena su nombre, dirección, teléfono, email, DNI, nº de Seguridad Social y un código interno de profesor así como los años que tiene de antigüedad impartiendo cada asignatura.
- Nos damos cuenta de que en un curso escolar, puede haber varios profesores responsables de una asignatura (por bajas, ceses, etc.); por lo que anotamos cuándo empezó a impartir dicho profesor la asignatura y cuando terminó (si no ha terminado, se dejaría vacío)

Asegúrate de que podemos averiguar gracias al diseño, que si buscamos a un profesor un día concreto (por ejemplo el 13 de Mayo de 2018) a una hora concreta (sexta hora), podríamos saber en qué aula va a estar.



* Registro civil
Se desea realizar una base de datos para almacenar la información del registro civil de una provincia.
- El registro debe guardar información de nacimientos, defunciones, matrimonios y divorcios.
- Los nacimientos se producen en una localidad en cierta fecha, de una madre y certificados por un facultativo. Es posible que el padre no sea conocido.
- Las defunciones se certifican por un médico o forense. Se producen en una localidad, en cierta fecha.
- Los matrimonios son certificados por un funcionario. Se celebran en una localidad y fecha concretas. Los matrimonios están compuestos por dos personas.
- Los divorcios se sancionan por un juez, en una localidad y fecha concretas.
- El registro civil también se encarga de expedir los libros de familia. Hay un libro de familia por cada pareja con hijos en común, aunque también pueden existir libros de familia monoparentales.
- Todos los hechos registrables se apuntan en los libros de registro. Cada hecho se apunta en un folio, dentro de un tomo de un libro. Dos hechos no pueden compartir el mismo folio.
- Las personas participantes en un hecho se identifican por nombre, apellidos, lugar de nacimiento, y, si están disponibles, DNI, nombre del padre y nombre de la madre.
- Los ciudadanos pueden requerir la expedición de certificados de cualquier hecho registrable. Para evitar un abuso en el servicio, se desean conocer los certificados que han sido expedidos para cada ciudadano, y en qué fecha.

* Agenda personal
Un gestor de correo electrónico maneja la siguiente información
- Los correos se almacenarán en carpetas, con cierto nombre. Una carpeta puede contener correos, u otras carpetas. Un correo o carpeta aparece en una sola carpeta. La carpeta de nivel superior no aparece en ninguna carpeta.
- Los correos recibidos tienen una fecha de envío, un remitente, un texto, varios ficheros adjuntos y varios destinatarios. Cada destinatario aparece como ENVIADO A o CON COPIA A. Los correos tienen un identificador único.
- Los correos están inicialmente marcados como no leídos. 
- Un correo puede ser la respuesta a un correo anterior (envíado o recibido). Cuando se responde a un correo, se incluye en el correo el identificador del correo respondido.
- Inicialmente, los correos recibidos se almacenan en la carpeta ENTRADA. El usuario puede crear reglas organizar los correos, especificando que los correos recibidos de cierto remitente se almacenan en cierta carpeta.
- Se guarda una lista de contactos. Por cada contacto se quiere conocer su nombre, apellidos, direcciones de correo, y dirección postal
- Se deben almacenar también los correos enviados. Los correos enviados tienen la misma información que los recibidos, y se guardan en la carpeta ENVIADOS
- Se desea que el usuario pueda organizar los correos por conversaciones (como GMail)



* Correo electrónico
Realiza un diagrama E-R del siguiente supuesto acerca de un servidor de correo electrónico:
- Un email puede tener varios destinatarios, pero solo un remitente
- Los destinatarios son de tres tipos
  - TO: Un destinatario directo
  - CC: indirecto en copia
  - CCO: como copia oculta a otros destinatarios
- Un email puede tener varios ficheros adjuntos
- De cada usuario se guarda su nombre de usuario y su nombre real. Cada usuario tiene una agenda donde apunta sus contactos.
  





* Empresa
  Realiza un diagrama E-R del siguiente supuesto acerca de los empleados de una empresa:
- De cada empleado se sabe su DNI, nombre, apellidos y sueldo anual.
- Cada empleado trabaja en un departamento, de los que se conoce el nombre.
- Cada departamento tiene un responsable, que es uno de los empleados de la empresa.
- La empresa desarrolla proyectos, que tienen un nombre y un presupuesto
- Cada proyecto tiene un responsable, y trabajan en él varios empleados.
- Un empleado puede ser responsable de varios proyectos. Un empleado puede trabajar en varios proyectos.
    
  
  


* Colección de cromos
  Realiza un diagrama E-R del siguiente supuesto acerca de un coleccionista de cromos:
- De cada colección quiere saber el año de publicación inicial del álbum, editorial, nombre y número total de cromos.
- Las colecciones se agrupan por temas: fútbol, series de televisión, películas \ldots
- Cada cromo poseido pertenece a una colección, tiene un número, una descripción y un estado de conservación
- Cada álbum poseido pertenece a una colección, y tiene un estado de conservación
- También se desea almacenar información del cromos y álbums no poseidos, como en una \textit{lista de deseos}
- Algunos cromos son especialmente difíciles de conseguir. Hay que conocer qué cromos son especialmente difíciles de cada colección, se posean ya o no.
- De los cromos especialmente difíciles de conseguir, se debe conocer su abundancia relativa respecto de los demás cromos de la colección y su precio de mercado.
  



* Sistema de ficheros Windows
Realiza un diagrama E-R del siguiente supuesto acerca del sistema de ficheros de un ordenador:
- El ordenador puede tener varias unidades: A:, B:, C: \ldots
- Cada unidad tiene un directorio raíz
- Tanto directorios como ficheros tienen:
  - Un nombre
  - Una fecha de creación
  - Unos permisos, que indican si cada usuario puede leerlos o si puede modificarlos.
- Un directorio puede contener otros ficheros y directorios.
- Un fichero tiene datos almacenados
- De cada usuario necesitamos saber el nombre interno del sistema y una descripción.  
  



* Autoescuela
Realiza un diagrama E-R del siguiente supuesto acerca de una autoescuela
- Se desea saber de cada alumno su nombre, apellidos, DNI y carnets de conducir que ya posee.
- Hay una batería de tests de prueba para los alumnos en fase teórica, que se identifican por un número
- Los alumnos se matriculan para conseguir cierto carnet (A, B, C, D \ldots)
- Cada alumno está en la fase teórica o práctica
  - Si está en la fase teórica, es necesario saber qué tests de prueba ha realizado ya, con su puntuación
  - Si está en la fase práctica, es necesario saber cuántas clases prácticas lleva.
- De cada clase práctica, hay que saber qué profesor acompañó a qué estudiante, y en qué fecha.
- De los profesores solo conocemos el nombre, que no se repite.
- De cada examen al que se presente un alumno (teórico o práctico), hay que saber el resultado (aprobado o no) y en qué fecha se realizó, y para qué tipo de carnet era.
  
  






