* Biblioteca
Crear un diseño ER que permita gestionar los datos de una biblioteca de modo que:

- Las personas socias de la biblioteca disponen de un código de socio y además necesitar almacenar su dni, dirección, teléfono, nombre y apellidos
- La biblioteca almacena libros que presta a los socios y socias, de ellos se almacena su título, su editorial, el año en el que se escribió el libro, el nombre completo del autor (o autores), el año en que se editó y en qué editorial fue y el ISBN.
- Necesitamos poder indicar si un volumen en la biblioteca está deteriorado o no
- Queremos controlar cada préstamo que se realiza almacenando la fecha en la que se realiza, la fecha tope para devolver (que son 15 días más que la fecha inicial) y la fecha real en la que se devuelve el libro


* Menú diario

Crear un esquema ER que represente un modelo para llevar los datos que maneja un restaurante de menús diarios. Teniendo en cuenta que:
- Sólo interesa llevar los datos de los menús diarios a la hora de la comida, nada más del restaurante
- Cada menús se compone de una serie de posibles platos. Cada plato se puede repetir en diferentes días. Los platos pueden ser primer plato, segundo plato o postre.
- De cada plato se almacena el nombre (por ejemplo /Arroz negro con setas/) y una pequeña descripción.
- De los menús almacenamos la fecha en la que se ofrece el menú, y el número de raciones de cada plato que se han servido ese día.
- Se almacena también la temperatura que hacía el día del menú para así poder analizar las temperaturas y los platos exitosos


* Horario
Crear un esquema ER que represente el funcionamiento de un centro escolar de formación profesional, teniendo en cuenta que:

- Sólo interesa llevar el control de ocupación de las aulas en el horario escolar
- El horario es de seis horas diarias y en la base de datos simplemente se anota si es la primera, segunda,… y el día de la semana del que hablamos (por ejemplo miércoles a tercera hora)
- Las asignaturas tienen un nombre, un código interno del centro y un código europeo.
- La misma asignatura se puede impartir en dos ciclos distintos y en ese caso tendría el mismo código europeo y nombre, pero el código interno sería distinto. Hace falta saber en qué curso del ciclo se imparte la asignatura
- Los ciclos tienen un nombre, pueden ser de grado superior,de grado medio o de iniciación profesional
- Las asignaturas en cada momento ocupan un aula, del que tenemos que almacenar un código de aula, un nombre (que no se repite), un número de aula (que tampoco se repite) y los metros que tiene. A una hora concreta de la semana, el aula puede estar vacía o bien ocuparse, pero sólo se puede ocupar por una asignatura
- Necesitamos saber y anotar en la base de datos si una asignatura requiere que antes se hayan aprobado otras, para poder matricularse en ella. Por ejemplo, Ampliación de Matemáticas de 2º a lo mejor requiere aprobar Matemáticas de 1º. Puede requerirse terminar más de una asignatura previamente para poder matricularse de una concreta.
- De los profesores se almacena su nombre, dirección, teléfono, email, DNI, nº de Seguridad Social y un código interno de profesor así como los años que tiene de antigüedad impartiendo cada asignatura.
- Nos damos cuenta de que en un curso escolar, puede haber varios profesores responsables de una asignatura (por bajas, ceses, etc.); por lo que anotamos cuándo empezó a impartir dicho profesor la asignatura y cuando terminó (si no ha terminado, se dejaría vacío)

Asegúrate de que podemos averiguar gracias al diseño, que si buscamos a un profesor un día concreto (por ejemplo el 13 de Mayo de 2018) a una hora concreta (sexta hora), podríamos saber en qué aula va a estar.



* Registro civil
Se desea realizar una base de datos para almacenar la información del registro civil de una provincia.
- El registro debe guardar información de nacimientos, defunciones, matrimonios y divorcios.
- Los nacimientos se producen en una localidad en cierta fecha, de una madre y certificados por un facultativo. Es posible que el padre no sea conocido.
- Las defunciones se certifican por un médico o forense. Se producen en una localidad, en cierta fecha.
- Los matrimonios son certificados por un funcionario. Se celebran en una localidad y fecha concretas. Los matrimonios están compuestos por dos personas.
- Los divorcios se sancionan por un juez, en una localidad y fecha concretas.
- El registro civil también se encarga de expedir los libros de familia. Hay un libro de familia por cada pareja con hijos en común, aunque también pueden existir libros de familia monoparentales.
- Todos los hechos registrables se apuntan en los libros de registro. Cada hecho se apunta en un folio, dentro de un tomo de un libro. Dos hechos no pueden compartir el mismo folio.
- Las personas participantes en un hecho se identifican por nombre, apellidos, lugar de nacimiento, y, si están disponibles, DNI, nombre del padre y nombre de la madre.
- Los ciudadanos pueden requerir la expedición de certificados de cualquier hecho registrable. Para evitar un abuso en el servicio, se desean conocer los certificados que han sido expedidos para cada ciudadano, y en qué fecha.

* Agenda personal
Un gestor de correo electrónico maneja la siguiente información
- Los correos se almacenarán en carpetas, con cierto nombre. Una carpeta puede contener correos, u otras carpetas. Un correo o carpeta aparece en una sola carpeta. La carpeta de nivel superior no aparece en ninguna carpeta.
- Los correos recibidos tienen una fecha de envío, un remitente, un texto, varios ficheros adjuntos y varios destinatarios. Cada destinatario aparece como ENVIADO A o CON COPIA A. Los correos tienen un identificador único.
- Los correos están inicialmente marcados como no leídos. 
- Un correo puede ser la respuesta a un correo anterior (envíado o recibido). Cuando se responde a un correo, se incluye en el correo el identificador del correo respondido.
- Inicialmente, los correos recibidos se almacenan en la carpeta ENTRADA. El usuario puede crear reglas organizar los correos, especificando que los correos recibidos de cierto remitente se almacenan en cierta carpeta.
- Se guarda una lista de contactos. Por cada contacto se quiere conocer su nombre, apellidos, direcciones de correo, y dirección postal
- Se deben almacenar también los correos enviados. Los correos enviados tienen la misma información que los recibidos, y se guardan en la carpeta ENVIADOS
- Se desea que el usuario pueda organizar los correos por conversaciones (como GMail)



* Correo electrónico
Realiza un diagrama E-R del siguiente supuesto acerca de un servidor de correo electrónico:
- Un email puede tener varios destinatarios, pero solo un remitente
- Los destinatarios son de tres tipos
  - TO: Un destinatario directo
  - CC: indirecto en copia
  - CCO: como copia oculta a otros destinatarios
- Un email puede tener varios ficheros adjuntos
- De cada usuario se guarda su nombre de usuario y su nombre real. Cada usuario tiene una agenda donde apunta sus contactos.
  





* Empresa
  Realiza un diagrama E-R del siguiente supuesto acerca de los empleados de una empresa:
- De cada empleado se sabe su DNI, nombre, apellidos y sueldo anual.
- Cada empleado trabaja en un departamento, de los que se conoce el nombre.
- Cada departamento tiene un responsable, que es uno de los empleados de la empresa.
- La empresa desarrolla proyectos, que tienen un nombre y un presupuesto
- Cada proyecto tiene un responsable, y trabajan en él varios empleados.
- Un empleado puede ser responsable de varios proyectos. Un empleado puede trabajar en varios proyectos.
    
  
  


* Colección de cromos
  Realiza un diagrama E-R del siguiente supuesto acerca de un coleccionista de cromos:
- De cada colección quiere saber el año de publicación inicial del álbum, editorial, nombre y número total de cromos.
- Las colecciones se agrupan por temas: fútbol, series de televisión, películas \ldots
- Cada cromo poseido pertenece a una colección, tiene un número, una descripción y un estado de conservación
- Cada álbum poseido pertenece a una colección, y tiene un estado de conservación
- También se desea almacenar información del cromos y álbums no poseidos, como en una \textit{lista de deseos}
- Algunos cromos son especialmente difíciles de conseguir. Hay que conocer qué cromos son especialmente difíciles de cada colección, se posean ya o no.
- De los cromos especialmente difíciles de conseguir, se debe conocer su abundancia relativa respecto de los demás cromos de la colección y su precio de mercado.
  



* Sistema de ficheros Windows
Realiza un diagrama E-R del siguiente supuesto acerca del sistema de ficheros de un ordenador:
- El ordenador puede tener varias unidades: A:, B:, C: \ldots
- Cada unidad tiene un directorio raíz
- Tanto directorios como ficheros tienen:
  - Un nombre
  - Una fecha de creación
  - Unos permisos, que indican si cada usuario puede leerlos o si puede modificarlos.
- Un directorio puede contener otros ficheros y directorios.
- Un fichero tiene datos almacenados
- De cada usuario necesitamos saber el nombre interno del sistema y una descripción.  
  



* Autoescuela
Realiza un diagrama E-R del siguiente supuesto acerca de una autoescuela
- Se desea saber de cada alumno su nombre, apellidos, DNI y carnets de conducir que ya posee.
- Hay una batería de tests de prueba para los alumnos en fase teórica, que se identifican por un número
- Los alumnos se matriculan para conseguir cierto carnet (A, B, C, D \ldots)
- Cada alumno está en la fase teórica o práctica
  - Si está en la fase teórica, es necesario saber qué tests de prueba ha realizado ya, con su puntuación
  - Si está en la fase práctica, es necesario saber cuántas clases prácticas lleva.
- De cada clase práctica, hay que saber qué profesor acompañó a qué estudiante, y en qué fecha.
- De los profesores solo conocemos el nombre, que no se repite.
- De cada examen al que se presente un alumno (teórico o práctico), hay que saber el resultado (aprobado o no) y en qué fecha se realizó, y para qué tipo de carnet era.
  
  







* Artículos y encargos
Una base de datos para una pequeña empresa debe contener información acerca de clientes, artículos y pedidos. Hasta el momento se registran los siguientes datos en documentos varios:
- Para cada cliente: Número de cliente (único), Direcciones de envío (varias por cliente), Saldo, Límite de crédito (depende del cliente, pero en ningún caso debe superar los 3.000.000 pts), Descuento.
- Para cada artículo: Número de artículo (único), Fábricas que lo distribuyen, Existencias de ese artículo en cada fábrica, Descripción del artículo.
- Para cada pedido: Cada pedido tiene una cabecera y el cuerpo del pedido. La cabecera está formada por el número de cliente, dirección de envío y fecha del pedido. El cuerpo del pedido son varias líneas, en cada línea se especifican el número del artículo pedido y la cantidad.
- Además, se ha determinado que se debe almacenar la información de las fábricas. Sin embargo, dado el uso de distribuidores, se usará: Número de la fábrica (único) y Teléfono de contacto. Y se desean ver cuántos artículos (en total) provee la fábrica. 
- También, por información estratégica, se podría incluir información de fábricas alternativas respecto de las que ya fabrican artículos para esta empresa.

Nota: Una dirección se entenderá como Nº, Calle y Ciudad. Una fecha incluye hora.

| NC | Número de cliente                  |
| DE | Dirección de envío                 |
| SC | Saldo cliente                      |
| LC | Límite crédito cliente             |
| DC | Descuento cliente                  |
| NA | Número de artículo                 |
| EA | Existencias de artículo en fábrica |
| DA | Descripción artículo               |
| FP | Fecha del pedido                   |
| CA | Cantidad de artículo               |
| NF | Número de fábrica                  |
| TF | Teléfono fábrica                   |
| FA | La fábrica es alternativa          |


Se pide hacer el diagrama ER para la base de datos que represente esta información.

* Sistema de ventas
Le contratan para hacer una BD que permita apoyar la gestión de un sistema de ventas. La empresa necesita llevar un control de proveedores, clientes, productos y ventas.

Un proveedor tiene nombre, dirección, teléfono y página web. Un cliente también tiene nombre, dirección, pero puede tener varios teléfonos de contacto. La dirección se entiende por calle, númer y ciudad.

Un producto tiene un id único, nombre, precio actual, stock y nombre del proveedor. Además se organizan en categorías, y cada producto va sólo en una categoría. Una categoría tiene id, nombre y descripción.

Por razones de contabilidad, se debe registrar la información de cada venta con un id, fecha, cliente, descuento y monto final. Además se debe guardar el precio al momento de la venta, la cantidad vendida y el monto total por el producto.

* Carreteras
Diseñar un esquema E/R que recoja la organización de una base de datos para contener la información sobre todas las carreteras del país, sabiendo que se deben cumplir las siguientes especificaciones:
- Las carreteras están divididas en varias categorías (locales, comerciales, regionales, nacionales, autovías, etc).
- Las carreteras se dividen en tramos. Un tramo siempre pertenece a una única carretera y no puede cambiar de carretera.
- Un tramo puede pasar por varias poblaciones, interesando conocer el Km de la carretera y la población donde empieza el tramo y en donde termina.
- Para los tramos que suponen principio o final de carretera, interesa saber si es que la carretera concluye físicamente o es que confluye en otra carretera. En este caso, interesa conocer con qué carretera confluye y en qué kilómetro, tramo y población.

* Sistema de vuelos
Obtener el diagrama E/R para un sistema de control de vuelos adaptado a las siguientes reglas de gestión (indicar las entidades, interrelaciones, etc., que se deducen de cada una de las reglas):
a) De cada aeropuerto se conoce su código, nombre, ciudad y país.
b) En cada aeropuerto pueden tomar tierra diversos modelos de aviones (el modelo de un avión determina su capacidad, es decir, el número de plazas.
c) En cada aeropuerto existe una colección de programas de vuelo. En cada programa de vuelo se indica el número de vuelo, línea aérea y días de la semana en que existe dicho vuelo.
d) Cada programa de vuelo despega de un aeropuerto y aterriza en otro.
e) Los números de vuelo son únicos para todo el mundo.
f) En cada aeropuerto hay múltiples aterrizajes y despegues. Todos los aeropuertos contemplados están en activo, es decir, tienen algún aterrizaje y algún despegue.
g) Cada vuelo realizado pertenece a un cierto programa de vuelo. Para cada vuelo se quiere conocer su fecha, plazas vacías y el modelo de avión utilizado.
h) Algunos programas de vuelo incorporan escalas técnicas intermedias entre los aeropuertos de salida y de llegada. Se entiende por escala técnica a un aterrizaje y despegue consecutivos sin altas ó bajas de pasajeros.
i) De cada vuelo se quieren conocer las escalas técnicas ordenadas asignándole a cada una un número de orden. Por ejemplo, el programa de vuelo 555 de Iberia con vuelos los lunes y jueves 
   - despega de Barajas-Madrid-España 
   - aterriza en Caudell-Sydney-Australia 
   - escalas técnicas: 
     1. Los Pradiños-Sao Paulo-Brasil
     2. El Emperador-Santiago-Chile
     3. Saint Kitts-Auckland-Nueva Zelanda.

** Modificación
¿Qué cambios se producirán en el caso anterior si en las escalas pudiesen bajar o subir pasajeros?

Explicar cómo se podría representar esta nueva situación.

* Olimpíadas
- Las sedes olímpicas se dividen en complejos deportivos.
- Los complejos deportivos se subdividen en aquellos en los que se desarrolla un único deporte y en los polideportivos.
- Los complejos polideportivos tienen áreas designadas para cada deporte con un indicador de localización (ejemplo: centro, esquina- NE, etc.).
- Un complejo tiene una localización, un jefe de organización individual y un área total ocupada.
- Para cada tipo de sede, se conservará el número de complejos junto con su presupuesto aproximado.
- Cada complejo celebra una serie de eventos (ejemplo: la pista del estadio puede celebrar muchas carreras distintas.).
- Para cada evento está prevista una fecha, duración, número de participantes, número de comisarios.
- Una lista de todos los comisarios se conservará junto con la lista de los eventos en los que esté involucrado cada comisario ya sea cumpliendo la tarea de juez u observador.
- Tanto para cada evento como para el mantenimiento se necesitará cierto equipamiento (ejemplo: arcos, pértigas, barras paralelas, etc).

* Educando S.A.
En la Empresa "Educando S.A." se lleva control de sus Bienes y Servicios. El interés primario es poder
hacer que los Bienes se manejen de forma rápida y con el menor grado de error. Para esto quien maneja
la sección de "Bienes y Suministros" plantea las siguientes condiciones del negocio para la construcción
de una base de datos:
- La Sección está dividida en tres (3) áreas: COMPRAS, ALMACEN, INVENTARIO.
- El área de Compras funciona de la siguiente forma:
    - Recibe las solicitudes de compras de las diferentes áreas de la empresa.
    - Cada solicitud tiene un responsable.
    - Cada solicitud es autorizada por el jefe del área y posteriormente por el Director Financiero.
    - Quien realiza una solicitud puede ser responsable de uno o varios centros de costos, conla salvedad de que él como empleado solo está adscrito a uno.
    - De la solicitud se debe diligenciar la siguiente información: Número de la solicitud (consecutivo), Fecha, Responsable (nombre y cédula), Centro de Costos, Rubro presupuestal del cual se descargará la compra. En cada solicitud se pueden discriminar uno o muchos ítems con la siguiente información: ítem, nombre del bien, cantidad solicitada, unidad de medida del bien, valor unitario y valor total. Cada solicitud debe ser totalizada.
    -  Cada bien es identificado por un código universal que es único y es de carácter devolutivo (suministro) o un bien inmueble.
    - Una vez diligenciada la solicitud es remitida al área de compras para realizar su correspondiente cotización.
    - Las cotizaciones son realizadas con uno o varios proveedores de los bienes solicitados.
    - Una vez la cotización definitiva está lista, se crea una orden contractual que maneja la siguiente información: Número de la orden contractual, nit y nombre del proveedor al cual se le va a realizar la compra, fecha de la orden, monto total de la orden, fecha de entrega. Cada orden puede tener asociado uno o varios ítems de la solicitud o solicitudes que van a ser despachadas. Cada ítem tiene la siguiente información: nombre del bien, cantidad solicitada, cantidad despachada, unidad de medida del bien, valor unitario y valor total.
    - La orden de compra es aprobada por el Director Financiero para que sea enviada al proveedor elegido.
- El área de Almacén funciona de la siguiente forma:
    - Su función principal es recepcionar los bienes que llegan de los proveedores y distribuirlos a las correspondientes áreas que realizaron las solicitudes de compras.
    - Cuando llega un proveedor mercancía, este hace una entrega física de los bienes, los cuales son comparados con la factura que este entrega y con la orden de compra correspondiente. Si esta acción es correcta se registra una entrada de almacén por cada factura relacionada, con la siguiente información: Número de Entrada, Fecha, Número de factura, Proveedor, Total Bienes, Valor Total (los totales deben coincidir con los de la factura). Adjunto a esta se discriminan los ítems recibidos con la siguiente información: nombre del bien, cantidad entregada.
    - Cuando el almacén decide despachar los bienes a las diferentes áreas solicitantes, registra cada una de las entregas en Salidas de Almacén con la siguiente información: Número de Salida, Empleado responsable del bien a entregar, fecha de salida, fecha de entrega. Por cada entrega se detalla cada uno de los ítems con la siguiente información: nombre del bien, cantidad entregada.
    - Una entrada de almacén puede generar muchas salidas de almacén, por ejemplo: Pueden ingresar 500 pacas de papel higiénico, pero como se debe repartir entre varias áreas, cada una requiere de una salida de almacén.
- El área de inventarios funciona de la siguiente forma:
    - Es la encargada de administrar y controlar la ubicación de los bienes dentro de la empresa, por esto antes de que el bien salga del almacén debe ser codificado a través de un código único que lo haga identificable dentro de la empresa.
    - La ubicación del bien se identifica por la siguiente información: responsable del bien, fecha de entrega, dirección del bien (ubicación).

* Problema 7: Torneo de Tenis Grand Slam
El sistema debe memorizar todos los encuentros que se han desarrollado desde que existe el torneo, así
como las siguientes características de estos.

- El Grand Slam se compone de cuatro torneos anuales que se celebran en Gran Bretaña, Estados Unidos,
Francia y Australia.
- En cada país se pueden desarrollar en distintos lugares (p. ej., en EE. UU. puededesarrollarse en Forest Hill o en Flashing Meadows).
- Cada partido tiene asociado un premio de consolación para el perdedor que dependerá de la fase en quese encuentre el torneo (p. ej., el perdedor de octavos de final puede ganar 5.000 dólares). El ganador dea final recibirá el premio correspondiente al torneo.
- Cada torneo tiene cinco modalidades: Individual masculino, individual femenino, dobles masculino, dobles femenino y dobles mixtos.
- También hay que tener en cuenta la nacionalidad de un jugador, de forma que éste puede ser apátrida o tener varias nacionalidades.

El sistema debe dar respuesta a las siguientes preguntas:
1. Dado un año y un torneo, composición y resultado de los partidos.
2. Lista de árbitros que participaron en el torneo.
3. Ganancias percibidas en premios por un jugador a lo largo del torneo.
4. Lista de entrenadores que han entrenado a un jugador a lo largo del torneo y fechas en las que lo hizo.

Ejemplos de acceso a la base de datos.
1. Connors gano Gerulaitis en Roland Garros en 1979 en cuartos de final en individuales masculinos por 6-3 4-6 7-5 6-0.
2. El señor Wilkinson arbitró ese partido.
3. Alemania ha ganado dos veces las individuales masculinas de Wimbledon. Borg ha ganado 2.000.000 de dólares a lo largo de su participación en el Grand Slam.
4. El ganado de Roland Garros de 1987 ganó 20.000 dólares.
5. Noah ha jugado cuatro veces en dobles mixtos con Mandlikova.

* Cines
Se desea crear un sitio web con información referente a las películas en cartel en las salas de una cadena de cines.
- De cada película, se almacena una ficha con su título de distribución, su título original, su género, el idioma original, si tiene subtítulos en español o no, los países de origen, el año de la producción, la url del sitio web de la película, la duración (en horas y minutos), la calificación (Apta todo público,+9 años, +15 años,+18 años), fecha de estreno, un resumen y un identificador de la película. 
- De cada película interesa conocer la lista de directores y el reparto, es decir para cada actor que trabaja, el nombre de todos los personajes que interpreta.
- Además interesa disponer de información sobre los directores y actores que trabajan en cada película.
  - De ambos, se conoce su nombre (que lo identifica) y su nacionalidad. 
  - Además se desea conocer en qué otras películas dirigieron o actuaron. 
  - Tenga en cuenta que hay personas que cumplen los dos roles.
- Los cines pueden tener más de una sala y cada semana cada uno de los cines envía la cartelera para dicha semana, indicando de detalle de las funciones. 
- Para cada función se conoce el día de la semana y la hora de comienzo, y obviamente la sala y la película que exhibe. 
- De cada sala se sabe el nombre, un número que la identifica dentro del cine y la cantidad de butacas que posee. 
- De cada cine se conoce el nombre que lo identifica, su dirección y teléfono para consultas.
- Algunos cines cuentan con promociones. Estas promociones dependen de la función. (Ej. De lunes a jueves antes de las 18 50% de descuento en la sala tal del cine tal para la película cual...La función del lunes a las 14 para la película tal en la sala cual, no se cobra a los escolares con túnica... ) 
- De cada promoción se conoce una descripción y el descuento que aplica.
- Además del resumen de la película que se incluye en la ficha interesa mostrar la opinión de las personas que vieron la película.
-  De cada opinión se conoce el nombre de la persona que la realiza, su edad, la fecha en que registró su opinión, la calificación que le dio a la película (Obra Maestra, Muy Buena, Buena, Regular, Mala) y el comentario propiamente dicho. 
