


* Preguntas a secretaría:
- *¿Cuántas citas simultáneas?* Parece que no se pueden simultanear citas
- *Cuánto tiempo para cada cita* He puesto 5 minutos
- *Horario de las citas* He puesto desde las 10:00 hasta las 13:00
- *Con cuánta antelación* He puesto 20 días laborables
- *¿pedimos teléfono, nombre, motivo de la cita...?*  Es obligatorio el nombre y correo electrónico. He puesto como opcional el móvil y el motivo de la cita.
  
* Más preguntas y asuntos
- Cancelación y modificación de citas:
    - Los alumnos, con el enlace enviado al email de la cita. /Si no se pone bien el email, solo puede cambiarlo secretaría/.
    - En secretaría, usando el [[https://outlook.office365.com/owa/calendar/764191242fe14cd0a1f1f729b8009ad7@iesavellaneda.onmicrosoft.com/e7779fe3b8fb4ac787e1021cd7733e7812998195332699752543/calendar.html][calendario de outlook]]
- No se pueden pedir citas para el mismo día      
- Quién pone los festivos?
- ¿va  a haber alguna validación o seguimiento de las citas?


* Para pedir cita

- Botón: Se puede añadir un botón abajo a  la derecha que pone *Pedir una cita con secretaría*
  #+begin_export html
    <!-- Principio del widget de globo de Calendly -->
  <link href="https://assets.calendly.com/assets/external/widget.css" rel="stylesheet">
  <script src="https://assets.calendly.com/assets/external/widget.js" type="text/javascript" async></script>
  <script type="text/javascript">window.onload = function() { Calendly.initBadgeWidget({ url: 'https://calendly.com/ies-alonso-avellaneda/cita-previa-en-secretaria', text: 'Pedir una cita con secretaría', color: '#00a2ff', textColor: '#ffffff', branding: false }); }</script>
  <!-- Final del widget de globo de Calendly -->
  #+end_export
- Enlace: Se puede poner un texto cualquiera en un enlace, como el siguiente:
  #+begin_export html
  <!-- Principio del widget de enlace de Calendly -->
  <link href="https://assets.calendly.com/assets/external/widget.css" rel="stylesheet">
  <script src="https://assets.calendly.com/assets/external/widget.js" type="text/javascript" async></script>
  <a href="" onclick="Calendly.initPopupWidget({url: 'https://calendly.com/ies-alonso-avellaneda/cita-previa-en-secretaria'});return false;">Pedir una cita con secretaría</a>
  <!-- Final del widget de enlace de Calendly -->
  #+end_export

Esto se puede poner en la web actual en una media hora. Para ello, necesito las claves de acceso.
  
* Cuenta en calendly  
Registrado con alvaro.gonzalezsotillo@iesavellaneda.onmicrosoft.com

He puesto un calendario de outlook de esa cuenta. Tiene integración con otros calendarios con ICS, lo que significa que se puede visualizar en Google Calendar, en Outlook, en Moodle...

- [[https://outlook.office365.com/owa/calendar/764191242fe14cd0a1f1f729b8009ad7@iesavellaneda.onmicrosoft.com/4fedc9422d9c43929d111ff9dd3ad77f1875808847706438936/S-1-8-2759839645-3663226375-497591825-2880854480/reachcalendar.ics][Enlace al calendario ICS]]
- [[https://outlook.office365.com/owa/calendar/764191242fe14cd0a1f1f729b8009ad7@iesavellaneda.onmicrosoft.com/e7779fe3b8fb4ac787e1021cd7733e7812998195332699752543/calendar.ics][Otro enlace distinto]], pero al mismo calendario


* Cómo lo verían en secretaría
  Pueden entrar a calendly o ver [[https://outlook.office365.com/owa/calendar/764191242fe14cd0a1f1f729b8009ad7@iesavellaneda.onmicrosoft.com/e7779fe3b8fb4ac787e1021cd7733e7812998195332699752543/calendar.html][esta página web con las citas ya puestas]]


* Descartado :noexport:
** inline              
#+begin_export html
<!-- Principio del widget integrado de Calendly -->
<div class="calendly-inline-widget" data-url="https://calendly.com/ies-alonso-avellaneda/cita-previa-en-secretaria?hide_gdpr_banner=1" style="min-width:320px;height:630px;"></div>
<script type="text/javascript" src="https://assets.calendly.com/assets/external/widget.js" async></script>
<!-- Final del widget integrado de Calendly -->
#+end_export
  
